/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finalproject;

/**
 * Represents a specific food item along with its nutritional values and category.
 */
public class Food extends Target{
    /**
     * The category of the food.
     */
    protected FoodCategory foodCategory;

    /**
     * The name of the food.
     */
    protected String name;

    /**
     * Constructs a new Food object with the specified parameters.
     *
     * @param foodCategory The category of the food.
     * @param name         The name of the food.
     * @param protein      The protein content of the food.
     * @param carb         The carbohydrate content of the food.
     * @param calories     The calorie content of the food.
     * @param fat          The fat content of the food.
     */
    public Food(FoodCategory foodCategory, String name, double protein, double carb, double calories, double fat) {
        super(protein, carb, calories, fat);
        this.foodCategory = foodCategory;
        this.name = name;
    }

    /**
     * Retrieves the category of the food.
     *
     * @return The category of the food.
     */
    public FoodCategory getFoodCategory() {
        return foodCategory;
    }

    /**
     * Sets the category of the food.
     *
     * @param foodCategory The category of the food.
     */
    public void setFoodCategory(FoodCategory foodCategory) {
        this.foodCategory = foodCategory;
    }

    /**
     * Retrieves the name of the food.
     *
     * @return The name of the food.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the food.
     *
     * @param name The name of the food.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Converts the Food object to a string representation.
     *
     * @return A string representation of the Food object.
     */
    @Override
    public String toString() {
        return foodCategory + "," + name + "," + protein + "," + carb + "," + calories + "," + fat;
    }
}

